### ISSUE TITLE
Gulp setup task not passing

### ISSUE THREAD

**Issue by josephdburdick** [meteorhybrid/mac#1]
Command on line 14 "'cp -r ../submodules/MacGap2/M* ../app/.meteor/local/mac-build'," attempts to recursively copy contents from the MacGap2 directory but nothing exists inside ../submodules/MacGap2 and fails.

**Comment by andrewreedy** [comment]
So when cloning a repo with submodules you have to add the --recursive flag. I'll add it to the readme.

**Comment by andrewreedy** [comment]
I updated the readme to make this more clear

**Comment by josephdburdick** [comment]
:+1:
